site_name: Awesome Fooocus
site_url: https://awesome-fooocus.netlify.app
site_description: A curated list of awesome Fooocus resources
site_author: Rajtilak Bhattacharjee
repo_name: rajtilakjee/awesome-fooocus
repo_url: https://github.com/rajtilakjee/awesome-fooocus

theme:
  name: material
  palette:
    primary: purple
    accent: indigo
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajtilakjee
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/rajtilakjee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajtilak
