site_name: Awesome Fooocus
site_url: https://awesome-fooocus.netlify.app
site_description: A curated list of awesome Fooocus resources
site_author: Rajtilak Bhattacharjee
repo_name: rajtilakjee/awesome-fooocus
repo_url: https://github.com/rajtilakjee/awesome-fooocus

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'deep purple'
      accent: 'yellow'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'lime'
      accent: 'yellow'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajtilakjee
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/rajtilakjee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajtilak
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
